version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - /var/www/foodgram/infra/.env

  backend:
    image: razuvaev/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/var/www/foodgram/backend/foodgram/static/
      - media_value:/var/www/foodgram/backend/foodgram/media/
    depends_on:
      - db
    env_file:
      - /var/www/foodgram/infra/.env

  frontend:
    image: razuvaev/foodgram_frontend:latest
    volumes:
      - ../frontend/:/var/www/foodgram/frontend/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/:/var/www/foodgram/frontend/
      - ../docs/:/var/www/foodgram/api/docs/
      - static_value:/var/www/foodgram/backend/foodgram/static/
      - media_value:/var/www/foodgram/backend/foodgram/media/
    depends_on:
      - frontend
  
volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:
