version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../infra/.env

  backend:
    image: razuvaev/foodgram-project-react:latest
    restart: always
    volumes:
      - static_value:var/www/app/static/
      - media_value:var/www/app/media/
    depends_on:
      - db
    env_file:
      - ../infra/.env

  frontend:
    image: razuvaev/foodgram_front:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:var/app/back_static/
      - media_value:var/app/back_media/
    depends_on:
      - frontend
  
volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:
